### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Legend23** [Sommerregen/grav-theme-developer#4]
@Sommerregen hi ^^

I tried to copy the folder as said on the tutorial, but once i try it on my wamp i have this error: 

"Error 404:Woops. Looks like this page doesn't exist"

I just copied the **themes** repository on the **_ user/themes/ _**
and copy **01.homes** (of the demo rep) to the **_ user/pages/ _**

I don't know why..

Thank you. 

regards

**Comment by Sommerregen** [comment]
Sorry for the long silence. I will investigate this. Maybe you forgot to set the new home page to ´home´?

**UPDATE:** This is the config file is use:

```yaml
home:
  alias: '/home'

pages:
  theme: developer
  markdown_extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
```
